// <auto-generated />
using System;
using Magic_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magic_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_WebAPI.Models.Villa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amenity = "Pool",
                            CreatedDate = new DateTime(2025, 9, 21, 21, 18, 20, 112, DateTimeKind.Local).AddTicks(4543),
                            Details = "TEST kjhrjhh",
                            ImageUrl = "",
                            Name = "Royals",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            Amenity = "Pool",
                            CreatedDate = new DateTime(2025, 9, 21, 21, 18, 20, 112, DateTimeKind.Local).AddTicks(4553),
                            Details = "TEST kjhrjhh",
                            ImageUrl = "",
                            Name = "Royals 2",
                            Occupancy = 3,
                            Rate = 2000.0,
                            Sqft = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            Amenity = "Pool",
                            CreatedDate = new DateTime(2025, 9, 21, 21, 18, 20, 112, DateTimeKind.Local).AddTicks(4555),
                            Details = "TEST kjhrjhh",
                            ImageUrl = "",
                            Name = "Royals 3",
                            Occupancy = 50,
                            Rate = 20000.0,
                            Sqft = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            Amenity = "Pool",
                            CreatedDate = new DateTime(2025, 9, 21, 21, 18, 20, 112, DateTimeKind.Local).AddTicks(4556),
                            Details = "TEST kjhrjhh",
                            ImageUrl = "",
                            Name = "Royals 4",
                            Occupancy = 500,
                            Rate = 200000.0,
                            Sqft = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            Amenity = "Pool",
                            CreatedDate = new DateTime(2025, 9, 21, 21, 18, 20, 112, DateTimeKind.Local).AddTicks(4558),
                            Details = "TEST kjhrjhh",
                            ImageUrl = "",
                            Name = "Royals 5",
                            Occupancy = 78,
                            Rate = 20099.0,
                            Sqft = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
